### ISSUE TITLE
Continuing the translation to pt-br

### ISSUE THREAD

**Issue by andrealmar** [crystal-lang-br/crystal-lang-br#4]
Hi @alanwillms did you stop the translation for pt-br ? I want to help. 

Thanks,

**Comment by alanwillms** [comment]
Hello @andrealmar we will be happy to accept your pull requests 😄

**Comment by muniz95** [comment]
eae man

Paramos de traduzir mais pela correria, mas o trabalho não acabou. Vou te colocar como membro da org

**Comment by andrealmar** [comment]
valeu obrigado.

**Comment by MatheusRich** [comment]
Hey guys, is this still alive?
